// This file is generated by Firebase
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2KEx5LAcli-Hlo_SmyROMHPEMBUInFmg',
    appId: '1:709845204442:android:aefc3ea6819d01fe4114e3',
    messagingSenderId: '709845204442',
    projectId: 'flutter-food-app-efdfc',
    storageBucket: 'flutter-food-app-efdfc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSy...', // Replace with your iOS API key
    appId: '1:123...', // Replace with your iOS app ID
    messagingSenderId: '123...', // Replace with your iOS sender ID
    projectId: 'flutter-food-app-efdfc',
    storageBucket: 'flutter-food-app-efdfc.firebasestorage.app',
    iosClientId: '123...', // Replace with your iOS client ID
    iosBundleId: 'com.example.flutterApplication1', // Replace with your bundle ID
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2KEx5LAcli-Hlo_SmyROMHPEMBUInFmg',
    appId: '1:709845204442:web:aefc3ea6819d01fe4114e3',
    messagingSenderId: '709845204442',
    projectId: 'flutter-food-app-efdfc',
    authDomain: 'flutter-food-app-efdfc.firebaseapp.com',
    storageBucket: 'flutter-food-app-efdfc.firebasestorage.app',
  );
}
